"""add challenge and challenge member tables

Revision ID: 38dec7a65fd8
Revises: eebc850ab333
Create Date: 2026-09-13 17:32:09.499813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38dec7a65fd8'
down_revision: Union[str, Sequence[str], None] = 'eebc850ab333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('invite_code', sa.String(length=20), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', name='visibility', length=20), nullable=False),
    sa.Column('duration_type', sa.Enum('DAYS_10', 'DAYS_20', 'DAYS_30', 'INDEFINITE', name='durationtype', length=20), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('active_days', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('late_join_policy', sa.Enum('CLEAN', 'INHERIT_MISSED', 'CLOSED', name='latejoinpolicy', length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='challengestatus', length=20), nullable=False),
    sa.Column('current_group_streak', sa.Integer(), nullable=False),
    sa.Column('best_group_streak', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_created_by'), 'challenges', ['created_by'], unique=False)
    op.create_index(op.f('ix_challenges_invite_code'), 'challenges', ['invite_code'], unique=True)
    op.create_table('challenge_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('CREATOR', 'ADMIN', 'MEMBER', name='memberrole', length=20), nullable=False),
    sa.Column('current_individual_streak', sa.Integer(), nullable=False),
    sa.Column('best_individual_streak', sa.Integer(), nullable=False),
    sa.Column('missed_days_count', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'user_id', name='uq_challenge_member_user')
    )
    op.create_index(op.f('ix_challenge_members_challenge_id'), 'challenge_members', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_challenge_members_user_id'), 'challenge_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challenge_members_user_id'), table_name='challenge_members')
    op.drop_index(op.f('ix_challenge_members_challenge_id'), table_name='challenge_members')
    op.drop_table('challenge_members')
    op.drop_index(op.f('ix_challenges_invite_code'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_created_by'), table_name='challenges')
    op.drop_table('challenges')
    # ### end Alembic commands ###

    # drop_table leaves the native enum types behind, so a later upgrade would
    # fail with "type already exists". Autogenerate never emits these.
    bind = op.get_bind()
    for enum_name in ('memberrole', 'challengestatus', 'latejoinpolicy', 'durationtype', 'visibility'):
        postgresql.ENUM(name=enum_name).drop(bind, checkfirst=True)
