"""add inherited missed days to challenge members

Revision ID: 4cf600f15fe8
Revises: f0e29cb58d43
Create Date: 2026-09-16 22:59:34.200562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf600f15fe8'
down_revision: Union[str, Sequence[str], None] = 'f0e29cb58d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing rows need a value before the column can be NOT NULL. The default is
    # then dropped so the database schema matches the model, which defaults in Python.
    op.add_column(
        'challenge_members',
        sa.Column('inherited_missed_days', sa.Integer(), nullable=False, server_default='0'),
    )
    op.alter_column('challenge_members', 'inherited_missed_days', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenge_members', 'inherited_missed_days')
    # ### end Alembic commands ###
