"""add membership exit and challenge cancellation

Revision ID: 63e7d12e455b
Revises: 4cf600f15fe8
Create Date: 2026-09-21 21:40:37.963533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63e7d12e455b'
down_revision: Union[str, Sequence[str], None] = '4cf600f15fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge_members', sa.Column('left_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('challenge_members', sa.Column('removed_by', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'challenge_members_removed_by_fkey', 'challenge_members', 'users', ['removed_by'], ['id'], ondelete='SET NULL'
    )
    op.add_column('challenges', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'cancelled_at')
    op.drop_constraint('challenge_members_removed_by_fkey', 'challenge_members', type_='foreignkey')
    op.drop_column('challenge_members', 'removed_by')
    op.drop_column('challenge_members', 'left_at')
    # ### end Alembic commands ###
