"""add check in and check in review tables

Revision ID: f0e29cb58d43
Revises: 6dd429a3131f
Create Date: 2026-09-15 22:16:35.004842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f0e29cb58d43'
down_revision: Union[str, Sequence[str], None] = '6dd429a3131f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_ins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('photo_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'APPROVED', 'REJECTED', name='checkinstatus', length=20), nullable=False),
    sa.Column('review_closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_check_in_challenge_user_date', 'check_ins', ['challenge_id', 'user_id', 'local_date'], unique=False)
    op.create_index(op.f('ix_check_ins_challenge_id'), 'check_ins', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_check_ins_user_id'), 'check_ins', ['user_id'], unique=False)
    op.create_table('check_in_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('check_in_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['check_in_id'], ['check_ins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('check_in_id', 'reviewer_id', name='uq_check_in_review_reviewer')
    )
    op.create_index(op.f('ix_check_in_reviews_check_in_id'), 'check_in_reviews', ['check_in_id'], unique=False)
    op.create_index(op.f('ix_check_in_reviews_reviewer_id'), 'check_in_reviews', ['reviewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_check_in_reviews_reviewer_id'), table_name='check_in_reviews')
    op.drop_index(op.f('ix_check_in_reviews_check_in_id'), table_name='check_in_reviews')
    op.drop_table('check_in_reviews')
    op.drop_index(op.f('ix_check_ins_user_id'), table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_challenge_id'), table_name='check_ins')
    op.drop_index('ix_check_in_challenge_user_date', table_name='check_ins')
    op.drop_table('check_ins')
    # ### end Alembic commands ###

    # Autogenerate never emits DROP TYPE, so without this the enum survives the
    # downgrade and the next upgrade fails with "type already exists".
    postgresql.ENUM(name='checkinstatus').drop(op.get_bind(), checkfirst=True)
